LoadPackage("GBNP","0",false);
SetInfoLevel(InfoGBNP,1);
SetInfoLevel(InfoGBNPTime,1);
F := Rationals;
A := FreeAssociativeAlgebraWithOne(F,"h","y","x","b","a");
g :=GeneratorsOfAlgebraWithOne(A);
h := g[1];
y := g[2];
x := g[3];
b := g[4];
a := g[5];;
weights := [1,1,1,1,1];
KI_gp := [a*a-h*h,a*x-h*h,x*a-h*h,b*y-h*h,y*b-h*h,b*b*b-h*h*h,a*b*a*b*a*b*a*b*a*b*a*b*a*b*a*b*a*b*a*b*a*b*a*b*a*b-h*h*h*h*h*h*h*h*h*h*h*h*h*h*h*h*h*h*h*h*h*h*h*h*h*h,a*b*b*a*b*a*b*b*a*b*a*b*b*a*b*a*b*b*a*b-h*h*h*h*h*h*h*h*h*h*h*h*h*h*h*h*h*h*h*h,a*h-h*a,b*h-h*b,x*h-h*x,y*h-h*y];
KI_np :=GP2NPList(KI_gp);
GB :=SGrobnerTrunc(KI_np,26,weights);
GBNP.ConfigPrint("h","y","x","b","a");
PrintNPList(GB);
Length(GB);
quit;