LoadPackage("GBNP","0",false);
SetInfoLevel(InfoGBNP,1);
SetInfoLevel(InfoGBNPTime,1);
F := Rationals;
A := FreeAssociativeAlgebraWithOne(F,"z","y","x");
g :=GeneratorsOfAlgebraWithOne(A);
z := g[1];
y := g[2];
x := g[3];;
weights := [1,1,1];
KI_gp := [z*z*z*z+y*x*y*x-x*y*y*x-3*z*y*x*z,x*x*x+y*x*y-x*y*x,z*y*x-x*y*z+z*x*z];
KI_np :=GP2NPList(KI_gp);
GB :=SGrobnerTrunc(KI_np,10,weights);
GBNP.ConfigPrint("z","y","x");
PrintNPList(GB);
Length(GB);
quit;